version: "3"
services:
  wealthy-backend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '8888:8080'
    volumes:
      - ./:/build
    image: wealthy-backend
    container_name: wealthy-backend-container