// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package routers

import (
	"github.com/semicolon-indonesia/wealthy-backend/api/v1/accounts"
	"github.com/semicolon-indonesia/wealthy-backend/api/v1/budgets"
	"github.com/semicolon-indonesia/wealthy-backend/api/v1/images"
	"github.com/semicolon-indonesia/wealthy-backend/api/v1/masters"
	"github.com/semicolon-indonesia/wealthy-backend/api/v1/statistics"
	"github.com/semicolon-indonesia/wealthy-backend/api/v1/transactions"
	"github.com/semicolon-indonesia/wealthy-backend/api/v1/wallets"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func Accounts(db *gorm.DB) *accounts.AccountController {
	accountRepository := accounts.NewAccountRepository(db)
	accountUseCase := accounts.NewAccountUseCase(accountRepository)
	accountController := accounts.NewAccountController(accountUseCase)
	return accountController
}

func Wallets(db *gorm.DB) *wallets.WalletController {
	walletRepository := wallets.NewWalletRepository(db)
	walletUseCase := wallets.NewWalletUseCase(walletRepository)
	walletController := wallets.NewWalletController(walletUseCase)
	return walletController
}

func Masters(db *gorm.DB) *masters.MasterController {
	masterRepository := masters.NewMasterRepository(db)
	masterUseCase := masters.NewMasterUseCase(masterRepository)
	masterController := masters.NewMasterController(masterUseCase)
	return masterController
}

func Transactions(db *gorm.DB) *transactions.TransactionController {
	transactionRepository := transactions.NewTransactionRepository(db)
	transactionUseCase := transactions.NewTransactionUseCase(transactionRepository)
	transactionController := transactions.NewTransactionController(transactionUseCase)
	return transactionController
}

func Budgets(db *gorm.DB) *budgets.BudgetController {
	budgetRepository := budgets.NewBudgetRepository(db)
	budgetUseCase := budgets.NewBudgetUseCase(budgetRepository)
	budgetController := budgets.NewBudgetController(budgetUseCase)
	return budgetController
}

func Statistics(db *gorm.DB) *statistics.StatisticController {
	statisticRepository := statistics.NewStatisticRepository(db)
	statisticUseCase := statistics.NewStatisticUseCase(statisticRepository)
	statisticController := statistics.NewStatisticController(statisticUseCase)
	return statisticController
}

func Images(db *gorm.DB) *images.ShowImageController {
	showImageRepository := images.NewShowImageRepository(db)
	showImageUseCase := images.NewShowImageUseCase(showImageRepository)
	showImageController := images.NewShowImageController(showImageUseCase)
	return showImageController
}
