// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package routers

import (
	"github.com/semicolon-indonesia/wealthy-backend/api/v1/accounts"
	"github.com/semicolon-indonesia/wealthy-backend/api/v1/wallets"
	"gorm.io/gorm"
)

// Injectors from wire.go:

func Accounts(db *gorm.DB) *accounts.AccountController {
	accountRepository := accounts.NewAccountRepository(db)
	accountUseCase := accounts.NewAccountUseCase(accountRepository)
	accountController := accounts.NewAccountController(accountUseCase)
	return accountController
}

func Wallets(db *gorm.DB) *wallets.WalletController {
	walletRepository := wallets.NewWalletRepository(db)
	walletUseCase := wallets.NewWalletUseCase(walletRepository)
	walletController := wallets.NewWalletController(walletUseCase)
	return walletController
}
